export const SEND_VERIFICATION_EMAIL = "SEND_VERIFICATION_EMAIL";
export const SEND_EMAIL_INVITATION = "SEND_EMAIL_INVITATION";
export const SEND_FORGOT_PASSWORD_EMAIL = "SEND_FORGOT_PASSWORD_EMAIL";
export const EMAIL_QUEUE = "EMAIL_QUEUE";
